### PR TITLE
Merge README and Style Guide, update Issue Template

### LINKED ISSUE #557: Update readme and issue-template files with new GitHub-UI-based contribution workflow
- [x] Update Readme
- [x] Update Issue template

### PR DESCRIPTION
**Pull request by HKuz**
Style Guide merged into the README and removed. I also added the gif+steps for the GitHub interface workflow. The issue template may need to be further refined as we figure out the best workflow for contributors. 

Closes #557

### CODE REVIEW

**Comment by HKuz** [comment]
Removed the URL structure section 👍

**Comment by Bouncey** [comment]
@HKuz is this good for a merge now?

**Comment by HKuz** [comment]
@Bouncey - should be, Quincy and I had a quick chat earlier today and he gave me that one change. Thank you!

**Comment by QuincyLarson** [comment]
@HKuz Awesome! Thanks!

**Pull request merged**
